### PR TITLE
Enable supportsReturning for sqlite.

### PR DESCRIPTION
**Pull request by waynebloss**
I updated all relevant tests and I believe they should pass.

### CODE REVIEW

**Comment by waynebloss** [comment]
I wasn't sure how to run the Github workflow action for testing on my fork. Now that I have figured it out, I am running tests on my fork and I see that there are some failures. I will work on fixing them.

**Comment by koskimas** [comment]
You can run the tests locally by just running `docker-compose up` and `npm test`

**Comment by waynebloss** [comment]
Thank you. The tests all pass locally now.

**Comment by koskimas** [comment]
Released in 0.21.5

**Pull request merged**
